// AvatarPreviewRenderer.cs
// ────────────────────────────────────────────────────────────────────────────
// Renders a PNG thumbnail for every avatar asset, so the wardrobe grid in the
// app can show the actual item instead of a placeholder hanger.
//
// The thumbnails are produced from the SAME FBX the game loads, which is the
// point: a hand-made icon set drifts the moment a mesh is re-exported, while
// these are regenerated by one menu click (or one CI command).
//
// Output: <unity project>/../../build/avatar_previews/<AssetName>.png
// (outside Assets/ — these are an artefact for the app/CDN, not project data).
//
// Batch mode needs a GPU context, so run WITHOUT -nographics:
//   Unity -batchmode -quit -projectPath <p> \
//         -executeMethod AvatarPreviewRenderer.CI_RenderPreviews
// ────────────────────────────────────────────────────────────────────────────

using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.Animations;
using UnityEngine.Playables;

public static class AvatarPreviewRenderer
{
    private const int Size = 512;

    [MenuItem("Hero/Avatar/Render Previews", false, 61)]
    public static void RenderPreviews()
    {
        var outputDir = Path.GetFullPath(Path.Combine(Application.dataPath, "../../../build/avatar_previews"));
        Directory.CreateDirectory(outputDir);

        var rendered = 0;

        // Items that live inside a shared wardrobe file: render the single mesh
        // the catalogue points at, under the catalogue's own id.
        foreach (var entry in AvatarCatalogMap.All())
        {
            var gender = entry.Key.Contains("_Male_") ? "Male" : "Female";
            var master = Resources.Load<GameObject>($"Avatar/{gender}/{entry.Value.File}");
            if (master == null) continue;

            var file = Path.Combine(outputDir, entry.Key + ".png");
            if (RenderMesh(master, entry.Value.Mesh, file)) rendered++;
        }

        // Packs that ship one FBX per item render whole.
        foreach (var gender in new[] { "Male", "Female" })
        foreach (var prefab in Resources.LoadAll<GameObject>($"Avatar/{gender}"))
        {
            if (prefab == null) continue;
            if (prefab.name.StartsWith("Wardrobe_")) continue; // covered above

            var file = Path.Combine(outputDir, prefab.name + ".png");
            if (Render(prefab, file, isBody: prefab.name.StartsWith("Body_"))) rendered++;
        }

        Debug.Log($"[hero] rendered {rendered} preview(s) to {outputDir}");
    }

    public static void CI_RenderPreviews() => RenderPreviews();

    /// Renders each body in its bind pose and in the idle clip, so a broken
    /// humanoid retarget (the hero folded in half) can be seen and fixed
    /// without a 20-minute export + device build round trip.
    [MenuItem("Hero/Avatar/Render Pose Check", false, 62)]
    public static void RenderPoseCheck()
    {
        var outputDir = Path.GetFullPath(Path.Combine(Application.dataPath, "../../../build/avatar_previews/pose"));
        Directory.CreateDirectory(outputDir);

        foreach (var gender in new[] { "Male", "Female" })
        {
            var prefab = Resources.Load<GameObject>($"Avatar/{gender}/Body_{gender}_01");
            if (prefab == null) continue;

            var clip = Resources.LoadAll<AnimationClip>($"Avatar/Animations/anim_idle_{gender.ToLowerInvariant()}")
                                .FirstOrDefault(c => c != null && !c.name.StartsWith("__"));

            var instance = Object.Instantiate(prefab);
            instance.hideFlags = HideFlags.HideAndDontSave;

            try
            {
                var animator = instance.GetComponentInChildren<Animator>();
                Debug.Log($"[hero/pose] {gender}: animator={(animator != null)}, " +
                          $"avatar={(animator != null && animator.avatar != null ? (animator.avatar.isHuman ? "humanoid" : "generic") : "none")}, " +
                          $"clip={(clip == null ? "MISSING" : clip.name + " " + (clip.isHumanMotion ? "(humanoid)" : "(generic)"))}");

                RenderInstance(instance, Path.Combine(outputDir, $"{gender}_bind.png"));

                if (clip == null || animator == null) continue;

                // Drive the clip through the SAME playable graph the game uses.
                // AnimationMode.SampleAnimationClip does not retarget humanoid
                // clips in edit mode — it silently leaves the bind pose, which
                // makes it useless for checking exactly what breaks at runtime.
                foreach (var time in new[] { 0f, 1.5f })
                {
                    var graph = PlayableGraph.Create("PoseCheck");
                    try
                    {
                        var output = AnimationPlayableOutput.Create(graph, "out", animator);
                        var clipPlayable = AnimationClipPlayable.Create(graph, clip);
                        clipPlayable.SetApplyFootIK(false);
                        output.SetSourcePlayable(clipPlayable);
                        graph.Evaluate(time);

                        RenderInstance(instance, Path.Combine(outputDir, $"{gender}_idle_{time:0.0}s.png"));
                    }
                    finally
                    {
                        if (graph.IsValid()) graph.Destroy();
                    }
                }
            }
            finally
            {
                Object.DestroyImmediate(instance);
            }
        }

        Debug.Log($"[hero/pose] written to {outputDir}");
    }

    public static void CI_RenderPoseCheck() => RenderPoseCheck();

    /// Assembles the hero the way the game does — body, face, a sample outfit —
    /// and renders him. This runs the real AvatarWardrobe, so what shows up
    /// here is what shows up on the device, minus the animation.
    [MenuItem("Hero/Avatar/Render Assembled Hero", false, 63)]
    public static void RenderAssembledHero()
    {
        var outputDir = Path.GetFullPath(Path.Combine(Application.dataPath, "../../../build/avatar_previews/hero"));
        Directory.CreateDirectory(outputDir);

        foreach (var gender in new[] { "male", "female" })
        {
            var root = new GameObject($"Hero_{gender}") { hideFlags = HideFlags.HideAndDontSave };
            var wardrobe = root.AddComponent<AvatarWardrobe>();

            try
            {
                wardrobe.SetGender(gender);
                if (wardrobe.Body == null)
                {
                    Debug.LogError($"[hero/assembled] {gender}: no body was built");
                    continue;
                }

                RenderInstance(root, Path.Combine(outputDir, $"{gender}_bare.png"));

                wardrobe.Equip(WardrobeSlot.Top, "01");
                wardrobe.Equip(WardrobeSlot.Bottom, "01");
                wardrobe.Equip(WardrobeSlot.Shoes, "01");
                wardrobe.Equip(WardrobeSlot.Hair, "01");

                RenderInstance(root, Path.Combine(outputDir, $"{gender}_dressed.png"));
                Debug.Log($"[hero/assembled] {gender}: rendered");
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        Debug.Log($"[hero/assembled] written to {outputDir}");
    }

    public static void CI_RenderAssembledHero() => RenderAssembledHero();

    /// Under URP a bare `camera.Render()` draws nothing — the scriptable
    /// pipeline only renders cameras it is asked about through a render
    /// request. The legacy call is kept as a fallback for a built-in pipeline.
    private static void SubmitRender(Camera camera, RenderTexture target)
    {
        var request = new UnityEngine.Rendering.Universal.UniversalRenderPipeline.SingleCameraRequest
        {
            destination = target,
        };

        if (UnityEngine.Rendering.RenderPipeline.SupportsRenderRequest(camera, request))
        {
            UnityEngine.Rendering.RenderPipeline.SubmitRenderRequest(camera, request);
            return;
        }

#pragma warning disable CS0618
        camera.Render();
#pragma warning restore CS0618
    }

    /// Renders one object out of a multi-item file, hiding everything else.
    private static bool RenderMesh(GameObject prefab, string meshName, string file)
    {
        var instance = Object.Instantiate(prefab);
        instance.hideFlags = HideFlags.HideAndDontSave;

        try
        {
            var kept = 0;
            foreach (var renderer in instance.GetComponentsInChildren<Renderer>(true))
            {
                var keep = meshName == null || renderer.name == meshName;
                renderer.enabled = keep;
                if (keep) kept++;
            }

            if (kept == 0)
            {
                Debug.LogWarning($"[hero] '{meshName}' not found in {prefab.name}");
                return false;
            }

            return RenderInstance(instance, file, isBody: false);
        }
        finally
        {
            Object.DestroyImmediate(instance);
        }
    }

    private static bool Render(GameObject prefab, string file, bool isBody)
    {
        var instance = Object.Instantiate(prefab);
        instance.hideFlags = HideFlags.HideAndDontSave;

        try
        {
            return RenderInstance(instance, file, isBody);
        }
        finally
        {
            Object.DestroyImmediate(instance);
        }
    }

    private static bool RenderInstance(GameObject instance, string file, bool isBody = true)
    {
        {
            var all = instance.GetComponentsInChildren<Renderer>(false);
            var renderers = System.Array.FindAll(all, r => r.enabled);
            if (renderers.Length == 0) return false;

            var bounds = renderers[0].bounds;
            foreach (var renderer in renderers) bounds.Encapsulate(renderer.bounds);

            var cameraGo = new GameObject("PreviewCamera") { hideFlags = HideFlags.HideAndDontSave };
            var camera = cameraGo.AddComponent<Camera>();
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = new Color(0f, 0f, 0f, 0f); // transparent PNG
            camera.fieldOfView = 30f;
            camera.nearClipPlane = 0.01f;

            // Bodies read best full-length; a garment is a small object that
            // should fill its card.
            var padding = isBody ? 1.15f : 1.35f;
            var extent = Mathf.Max(bounds.size.x, bounds.size.y, 0.01f) * padding;
            var distance = extent / (2f * Mathf.Tan(camera.fieldOfView * 0.5f * Mathf.Deg2Rad));

            camera.transform.position = bounds.center + new Vector3(0f, 0f, distance);
            camera.transform.LookAt(bounds.center);
            camera.farClipPlane = distance * 4f;

            var lightGo = new GameObject("PreviewLight") { hideFlags = HideFlags.HideAndDontSave };
            var light = lightGo.AddComponent<Light>();
            light.type = LightType.Directional;
            light.intensity = 1.4f;
            light.transform.rotation = Quaternion.Euler(30f, 200f, 0f);

            var target = new RenderTexture(Size, Size, 24, RenderTextureFormat.ARGB32)
            {
                antiAliasing = 4,
            };

            camera.targetTexture = target;
            SubmitRender(camera, target);

            var previous = RenderTexture.active;
            RenderTexture.active = target;
            var texture = new Texture2D(Size, Size, TextureFormat.RGBA32, false);
            texture.ReadPixels(new Rect(0, 0, Size, Size), 0, 0);
            texture.Apply();
            RenderTexture.active = previous;

            File.WriteAllBytes(file, texture.EncodeToPNG());

            camera.targetTexture = null;
            Object.DestroyImmediate(texture);
            target.Release();
            Object.DestroyImmediate(target);
            Object.DestroyImmediate(cameraGo);
            Object.DestroyImmediate(lightGo);
            return true;
        }
    }
}
